In [133]:
from empiricaldist import Pmf

In [134]:
def update_dice(pmf,data):
    """새로운 데이터를 기반으로 pmf를 갱신함"""
    hypos = pmf.qs
    likelihood = 1/ hypos
    impossible = (data > hypos)
    likelihood[impossible] = 0
    pmf *= likelihood
    pmf.normalize()

In [135]:
coin = Pmf()
coin['heads'] = 1/2
coin['tails'] = 1/2
coin

heads    0.5
tails    0.5
Name: , dtype: float64

In [136]:
die = Pmf.from_seq([1,2,3,4,5,6])
die

1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: , dtype: float64

In [137]:
letters = Pmf.from_seq(list('Mississippi'))

In [138]:
letters

M    0.090909
i    0.363636
p    0.181818
s    0.363636
Name: , dtype: float64

In [139]:
prior = Pmf.from_seq(['Bowl 1', 'Bowl 2'])
prior

Bowl 1    0.5
Bowl 2    0.5
Name: , dtype: float64

In [140]:
likelihood_vanilla = [0.75,0.5]
posterior = prior * likelihood_vanilla
posterior

Bowl 1    0.375
Bowl 2    0.250
Name: , dtype: float64

In [141]:
posterior.normalize()

0.625

In [142]:
posterior

Bowl 1    0.6
Bowl 2    0.4
Name: , dtype: float64

In [143]:
posterior *= likelihood_vanilla
posterior.normalize()
posterior

Bowl 1    0.692308
Bowl 2    0.307692
Name: , dtype: float64

In [144]:
likelihood_chocolate = [0.25,0.5]

In [145]:
posterior *= likelihood_chocolate
posterior.normalize()
posterior

Bowl 1    0.529412
Bowl 2    0.470588
Name: , dtype: float64

In [146]:
import numpy as np
hypos = np.arange(101)

In [147]:
prior = Pmf(1,hypos)
prior.normalize()
prior


0      0.009901
1      0.009901
2      0.009901
3      0.009901
4      0.009901
         ...   
96     0.009901
97     0.009901
98     0.009901
99     0.009901
100    0.009901
Name: , Length: 101, dtype: float64

In [148]:
prior.tail()

98     0.009901
99     0.009901
100    0.009901
Name: , dtype: float64

In [149]:
likelihood_vanilla = hypos/100
likelihood_vanilla[:5] 


array([0.  , 0.01, 0.02, 0.03, 0.04])

In [150]:
posterior1 = prior * likelihood_vanilla
posterior1.normalize()
posterior1.head()

0    0.000000
1    0.000198
2    0.000396
Name: , dtype: float64

In [151]:
posterior2 = posterior1 * likelihood_vanilla
posterior2.normalize()

0.6699999999999999

In [152]:
posterior2

0      0.000000
1      0.000003
2      0.000012
3      0.000027
4      0.000047
         ...   
96     0.027238
97     0.027808
98     0.028385
99     0.028967
100    0.029555
Name: , Length: 101, dtype: float64

In [153]:
likelihood_chocolate = 1 - hypos/100
posterior3 = posterior2 * likelihood_chocolate
posterior3.normalize()

0.2462686567164179

In [154]:
posterior3.idxmax()

67

In [155]:
posterior3.max_prob()

67

In [156]:
hypos = [6,8,12]

In [157]:
prior = Pmf(1/3,hypos)


In [158]:
prior.qs

array([ 6,  8, 12], dtype=int64)

In [159]:
prior.ps

array([0.33333333, 0.33333333, 0.33333333])

In [160]:
likelihood1 = 1/6,1/8,1/12

In [161]:
posterior = prior * likelihood1
posterior.normalize()
posterior


6     0.444444
8     0.333333
12    0.222222
Name: , dtype: float64

In [162]:
likelihood2 = 0,1/8,1/12

In [163]:
posterior *= likelihood2
posterior.normalize()
posterior

6     0.000000
8     0.692308
12    0.307692
Name: , dtype: float64

In [164]:
pmf = prior.copy()
pmf

6     0.333333
8     0.333333
12    0.333333
Name: , dtype: float64

In [165]:
update_dice(pmf,1)
update_dice(pmf,7)
pmf

6     0.000000
8     0.692308
12    0.307692
Name: , dtype: float64